### ISSUE TITLE
Error handler not wokring

### ISSUE THREAD

**Issue by imsorx** [L2jLiga/fastify-decorators#594]
### **Project Packages version -**
```
  "dependencies": {
    "bcryptjs": "^2.4.3",
    "fastify": "^3.14.2",
    "fastify-cors": "^5.2.0",
    "fastify-decorators": "^3.10.0",
    "fastify-helmet": "^5.3.2",
    "fastify-oas": "^3.0.8",
    "jsonwebtoken": "^8.5.1",
    "mongoose": "5.12.3"
  },
  "devDependencies": {
    "@types/babel__core": "^7.1.14",
    "@types/cors": "^2.8.10",
    "@types/jest": "^26.0.22",
    "@types/node": "^14.14.37",
    "jest": "^26.6.3",
    "nodemon": "^2.0.7",
    "ts-jest": "^26.5.4",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.4"
  }
```

### **Expected behavior** -
return **400** response with body ```{ message : 'User not found' }```

### Actual behavior
process exit with error
```
Error: User not found
    at /grid-api/src/dao/user.ts:12:22
    at Generator.next (<anonymous>)
    at fulfilled (/grid-api/src/dao/user.ts:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### **server.ts -** 
```
server.register(bootstrap,{
  directory: resolve('src','controllers'),
  mask:/\.controller\./
})

server.setErrorHandler((error, req, res) => {
  res.code(500).send({ message: error.toString() });
});
```

### **auth.controller.ts -**
```
@Controller('/auth')
export default class AuthController {
  @POST('/login', { schema })
  async get(request: FastifyRequest<{ Body: { name: number } }>, reply: FastifyReply) {
    return reply.send(login(request.body));
  }

  @ErrorHandler(UserError)
  errorHandler(error: UserError, request: FastifyRequest, reply: FastifyReply) {
    reply.status(400).send({
      message: error.message
    });
  }
}
```
### login method -
```
export const login = async (data: object) => {
    const user = await User.findOne({ email: data['email'] });

    if (!user) throw new UserError('User not found');

    await compare(data['password'], user.password);

    return {
        ...user.toObject(),
        token: user.generateToken()
    };
}
```

### **UserError -** 
```
export class UserError extends Error {
    constructor(public message: string) {
        super(message);
    }
}
```

### **Environment** - 
- Docker container - 4.1.1
- Nodejs - 17.1.0

**Comment by imsorx** [comment]
try...catch 😅
